# Generated by Django 4.2.4 on 2023-09-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название фирменного знака')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Имя покупателя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=225, verbose_name='Адрес')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Старая цена')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, verbose_name='Статус')),
                ('depart', models.CharField(blank=True, max_length=225, verbose_name='Упаковка')),
                ('article', models.CharField(blank=True, max_length=225, verbose_name='Артикуль')),
                ('grade', models.CharField(blank=True, max_length=225, verbose_name='Класс')),
                ('hieght', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('flower_size', models.CharField(blank=True, max_length=225, verbose_name='Размер цветка')),
                ('flowering_period', models.CharField(blank=True, max_length=100, verbose_name='Период')),
                ('landing_place', models.CharField(blank=True, max_length=100, verbose_name='Место посадки')),
                ('frost_resistance', models.CharField(blank=True, max_length=100, verbose_name='Морозостойкость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_1.brand', verbose_name='Фирменный знак')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_1.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lesson_1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='lesson_1.product')),
            ],
        ),
    ]
