# Generated by Django 4.2.4 on 2023-09-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0002_rename_hieght_product_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson_1.brand', verbose_name='Фирменный знак'),
        ),
    ]
