# Generated by Django 4.2.4 on 2023-09-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_create',
        ),
    ]
